title: Init87
email: cobra.rev.9@gmail.com
description: "A learning phase to completely internalise the very essence till the memory of C."
baseurl: "/Init87"
url: "https://cobra-r9.github.io"
github_username: cobra-r9

theme: minima
plugins:
  - jekyll-feed

sidebar:
  - title: "Memory"
    id: "memory"
    links:
      - text: "0.0 — Memory Init"
        url: "/memory/part0/0.0.md"
  - title: "Part 0 — Foundations"
    id: "part0"
    links:
      - text: "0.0 — Initializing"
        url: "/part0/0.0.md"

